"use client";

import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { theme } from "@/theme/theme";
import Nav_Bar from "@/component/Nav_Bar";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ChakraProvider theme={theme}>
					<Nav_Bar />
					{children}
				</ChakraProvider>
			</body>
		</html>
	);
}
